export const mock_articles = [
  {
    uri: "nyt://article/b14f0005-94d3-5d83-b035-5cea25661a9b",
    url: "https://www.nytimes.com/2024/03/30/opinion/trump-god-religion-easter.html",
    id: 100000009388644,
    asset_id: 100000009388644,
    source: "New York Times",
    published_date: "2024-03-30",
    updated: "2024-04-01 14:11:49",
    section: "Opinion",
    subsection: "",
    nytdsection: "opinion",
    adx_keywords:
      "Bible;Frauds and Swindling;Religion and Belief;Conspiracy Theories;Presidential Election of 2024;United States Politics and Government;Trump, Donald J",
    column: null,
    byline: "By Maureen Dowd",
    type: "Article",
    title: "Donald Trump, Blasphemous Bible Thumper",
    abstract:
      "Trump is, as the nuns who taught me used to say, “a bold, brazen piece.”",
    des_facet: [
      "Bible",
      "Frauds and Swindling",
      "Religion and Belief",
      "Conspiracy Theories",
      "Presidential Election of 2024",
      "United States Politics and Government",
    ],
    org_facet: [],
    per_facet: ["Trump, Donald J"],
    geo_facet: [],
    media: [
      {
        type: "image",
        subtype: "photo",
        caption: "",
        copyright: "Illustration by Sam Whitney/The New York Times",
        approved_for_syndication: 1,
        "media-metadata": [
          {
            url: "https://static01.nyt.com/images/2024/03/31/opinion/30dowd-image/30dowd-image-thumbStandard.jpg",
            format: "Standard Thumbnail",
            height: 75,
            width: 75,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/31/opinion/30dowd-image/30dowd-image-mediumThreeByTwo210.jpg",
            format: "mediumThreeByTwo210",
            height: 140,
            width: 210,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/31/opinion/30dowd-image/30dowd-image-mediumThreeByTwo440.jpg",
            format: "mediumThreeByTwo440",
            height: 293,
            width: 440,
          },
        ],
      },
    ],
    eta_id: 0,
    showDetails: false,
  },
  {
    showDetails: false,
    uri: "nyt://article/01fe6f8b-6569-5c80-8b08-0d849e180b85",
    url: "https://www.nytimes.com/2024/03/28/opinion/kamala-harris-puerto-rico.html",
    id: 100000009381649,
    asset_id: 100000009381649,
    source: "New York Times",
    published_date: "2024-03-28",
    updated: "2024-03-29 12:25:19",
    section: "Opinion",
    subsection: "",
    nytdsection: "opinion",
    adx_keywords:
      "United States Politics and Government;Federal-State Relations (US);Hurricane Maria (2017);Floods;Tax Credits, Deductions and Exemptions;Polls and Public Opinion;Harris, Kamala D;Puerto Rico",
    column: null,
    byline: "By Yarimar Bonilla",
    type: "Article",
    title: "Kamala Harris’s Epic Fail in Puerto Rico",
    abstract:
      "While she did not toss paper towels, her visit was what Puerto Ricans call a papelón — an embarrassing spectacle.",
    des_facet: [
      "United States Politics and Government",
      "Federal-State Relations (US)",
      "Hurricane Maria (2017)",
      "Floods",
      "Tax Credits, Deductions and Exemptions",
      "Polls and Public Opinion",
    ],
    org_facet: [],
    per_facet: ["Harris, Kamala D"],
    geo_facet: ["Puerto Rico"],
    media: [
      {
        type: "image",
        subtype: "photo",
        caption: "",
        copyright: "Drew Angerer/Agence France-Presse — Getty Images",
        approved_for_syndication: 1,
        "media-metadata": [
          {
            url: "https://static01.nyt.com/images/2024/03/29/multimedia/28bonilla-wclj/28bonilla-wclj-thumbStandard.jpg",
            format: "Standard Thumbnail",
            height: 75,
            width: 75,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/29/multimedia/28bonilla-wclj/28bonilla-wclj-mediumThreeByTwo210.jpg",
            format: "mediumThreeByTwo210",
            height: 140,
            width: 210,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/29/multimedia/28bonilla-wclj/28bonilla-wclj-mediumThreeByTwo440.jpg",
            format: "mediumThreeByTwo440",
            height: 293,
            width: 440,
          },
        ],
      },
    ],
    eta_id: 0,
  },
  {
    showDetails: false,
    uri: "nyt://article/422f15a0-8a24-5420-9f1a-c2897645a0f8",
    url: "https://www.nytimes.com/2024/03/27/nyregion/trump-social-media-attack.html",
    id: 100000009384814,
    asset_id: 100000009384814,
    source: "New York Times",
    published_date: "2024-03-27",
    updated: "2024-03-28 13:52:22",
    section: "New York",
    subsection: "",
    nytdsection: "new york",
    adx_keywords:
      "New York State Criminal Case Against Trump (71543-23);Social Media;Hoaxes and Pranks;Rumors and Misinformation;Trump, Donald J;Merchan, Juan M;Truth Social (Social Network);X (Formerly Twitter)",
    column: null,
    byline: "By Jesse McKinley and Ben Protess",
    type: "Article",
    title: "Trump Spreads Apparent Hoax in Attacking Judge’s Daughter",
    abstract:
      "Donald Trump said a photo of him behind bars on Loren Merchan’s X account meant he could not get a fair trial, but a court official said someone had appropriated the account.",
    des_facet: [
      "New York State Criminal Case Against Trump (71543-23)",
      "Social Media",
      "Hoaxes and Pranks",
      "Rumors and Misinformation",
    ],
    org_facet: ["Truth Social (Social Network)", "X (Formerly Twitter)"],
    per_facet: ["Trump, Donald J", "Merchan, Juan M"],
    geo_facet: [],
    media: [
      {
        type: "image",
        subtype: "photo",
        caption:
          "Former U.S. President Donald Trump is subject to a gag order in his Manhattan criminal trial, but the judge and his family are not included in the order.",
        copyright: "Pool photo by Justin Lane",
        approved_for_syndication: 1,
        "media-metadata": [
          {
            url: "https://static01.nyt.com/images/2024/03/26/multimedia/27NY-MERCHAN-trump/26trump-trial-01-bklp-thumbStandard.jpg",
            format: "Standard Thumbnail",
            height: 75,
            width: 75,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/26/multimedia/27NY-MERCHAN-trump/26trump-trial-01-bklp-mediumThreeByTwo210.jpg",
            format: "mediumThreeByTwo210",
            height: 140,
            width: 210,
          },
          {
            url: "https://static01.nyt.com/images/2024/03/26/multimedia/27NY-MERCHAN-trump/26trump-trial-01-bklp-mediumThreeByTwo440.jpg",
            format: "mediumThreeByTwo440",
            height: 293,
            width: 440,
          },
        ],
      },
    ],
    eta_id: 0,
  },
];
